import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

const sora = Sora({
  variable: "--font-prompt-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "LivroSaaS",
  description: "Generated by NextJs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
